export const countryArray = [
  {name: 'USA'},
  {name: 'India'},
  {name: 'Brazil'},
  {name: 'Russia'},
  {name: 'Peru'},
  {name: 'Colombia'},
  {name: 'Mexico'},
  {name: 'Spain'},
  {name: 'South Africa'},
  {name: 'Argentina'},
  {name: 'Chile'},
  {name: 'France'},
  {name: 'Iran'},
  {name: 'UK'},
  {name: 'Bangladesh'},
  {name: 'Saudi Arabia'},
  {name: 'Iraq'},
  {name: 'Pakistan'},
  {name: 'Turkey'},
  {name: 'Italy'},
  {name: 'Philippines'},
  {name: 'Germany'},
  {name: 'Indonesia'},
  {name: 'Israel'},
  {name: 'Ukraine'},
  {name: 'Canada'},
  {name: 'Bolivia'},
  {name: 'Ecuador'},
  {name: 'Qatar'},
  {name: 'Romania'},
  {name: 'Dominican Republic'},
  {name: 'Kazakhstan'},
  {name: 'Panama'},
  {name: 'Egypt'},
  {name: 'Belgium'},
  {name: 'Kuwait'},
  {name: 'Morocco'},
  {name: 'Netherlands'},
  {name: 'Oman'},
  {name: 'Sweden'},
  {name: 'Guatemala'},
  {name: 'UAE'},
  {name: 'Poland'},
  {name: 'Japan'},
  {name: 'Belarus'},
  {name: 'Honduras'},
  {name: 'Portugal'},
  {name: 'Ethiopia'},
  {name: 'Venezuela'},
  {name: 'Bahrain'},
  {name: 'Nepal'},
  {name: 'Costa Rica'},
  {name: 'Singapore'},
  {name: 'Nigeria'},
  {name: 'Uzbekistan'},
  {name: 'Algeria'},
  {name: 'Switzerland'},
  {name: 'Czechia'},
  {name: 'Armenia'},
  {name: 'Moldova'},
  {name: 'Ghana'},
  {name: 'Kyrgyzstan'},
  {name: 'Azerbaijan'},
  {name: 'Afghanistan'},
  {name: 'Austria'},
  {name: 'Kenya'},
  {name: 'Palestine'},
  {name: 'Serbia'},
  {name: 'Ireland'},
  {name: 'Paraguay'},
  {name: 'Lebanon'},
  {name: 'El Salvador'},
  {name: 'Libya'},
  {name: 'Australia'},
  {name: 'Bosnia and Herzegovina'},
  {name: 'S. Korea'},
  {name: 'Denmark'},
  {name: 'Cameroon'},
  {name: 'Ivory Coast'},
  {name: 'Bulgaria'},
  {name: 'Hungary'},
  {name: 'North Macedonia'},
  {name: 'Madagascar'},
  {name: 'Greece'},
  {name: 'Croatia'},
  {name: 'Senegal'},
  {name: 'Zambia'},
  {name: 'Sudan'},
  {name: 'Norway'},
  {name: 'Albania'},
  {name: 'DRC'},
  {name: 'Namibia'},
  {name: 'Guinea'},
  {name: 'Malaysia'},
  {name: 'French Guiana'},
  {name: 'Maldives'},
  {name: 'Tajikistan'},
  {name: 'Tunisia'},
  {name: 'Finland'},
  {name: 'Gabon'},
  {name: 'Haiti'},
  {name: 'Luxembourg'},
  {name: 'Montenegro'},
  {name: 'Zimbabwe'},
  {name: 'Mauritania'},
  {name: 'Slovakia'},
  {name: 'Mozambique'},
  {name: 'Uganda'},
  {name: 'Malawi'},
  {name: 'Djibouti'},
  {name: 'Eswatini'},
  {name: 'Cabo Verde'},
  {name: 'Hong Kong'},
  {name: 'Cuba'},
  {name: 'Equatorial Guinea'},
  {name: 'Congo'},
  {name: 'Nicaragua'},
  {name: 'Myanmar'},
  {name: 'CAR'},
  {name: 'Jamaica'},
  {name: 'Suriname'},
  {name: 'Rwanda'},
  {name: 'Jordan'},
  {name: 'Slovenia'},
  {name: 'Angola'},
  {name: 'Trinidad and Tobago'},
  {name: 'Syria'},
  {name: 'Lithuania'},
  {name: 'Mayotte'},
  {name: 'Gambia'},
  {name: 'Thailand'},
  {name: 'Aruba'},
  {name: 'Guadeloupe'},
  {name: 'Somalia'},
  {name: 'Georgia'},
  {name: 'Sri Lanka'},
  {name: 'Réunion'},
  {name: 'Bahamas'},
  {name: 'Mali'},
  {name: 'Estonia'},
  {name: 'Malta'},
  {name: 'South Sudan'},
  {name: 'Botswana'},
  {name: 'Iceland'},
  {name: 'Guinea-Bissau'},
  {name: 'Benin'},
  {name: 'Sierra Leone'},
  {name: 'Guyana'},
  {name: 'Yemen'},
  {name: 'Uruguay'},
  {name: 'New Zealand'},
  {name: 'Burkina Faso'},
  {name: 'Togo'},
  {name: 'Belize'},
  {name: 'Cyprus'},
  {name: 'Andorra'},
  {name: 'Latvia'},
  {name: 'Lesotho'},
  {name: 'Liberia'},
  {name: 'French Polynesia'},
  {name: 'Niger'},
  {name: 'Chad'},
  {name: 'Martinique'},
  {name: 'Vietnam'},
  {name: 'Sao Tome and Principe'},
  {name: 'San Marino'},
  {name: 'Diamond Princess'},
  {name: 'Turks and Caicos'},
  {name: 'Channel Islands'},
  {name: 'Sint Maarten'},
  {name: 'Papua New Guinea'},
  {name: 'Tanzania'},
  {name: 'Taiwan'},
  {name: 'Burundi'},
  {name: 'Comoros'},
  {name: 'Faeroe Islands'},
  {name: 'Mauritius'},
  {name: 'Eritrea'},
  {name: 'Gibraltar'},
  {name: 'Isle of Man'},
  {name: 'Saint Martin'},
  {name: 'Mongolia'},
  {name: 'Cambodia'},
  {name: 'Bhutan'},
  {name: 'Curaçao'},
  {name: 'Cayman Islands'},
  {name: 'Monaco'},
  {name: 'Barbados'},
  {name: 'Bermuda'},
  {name: 'Brunei'},
  {name: 'Seychelles'},
  {name: 'Liechtenstein'},
  {name: 'Antigua and Barbuda'},
  {name: 'British Virgin Islands'},
  {name: 'St. Vincent Grenadines'},
  {name: 'Macao'},
  {name: 'Caribbean Netherlands'},
  {name: 'Fiji'},
  {name: 'Saint Lucia'},
  {name: 'Timor-Leste'},
  {name: 'New Caledonia'},
  {name: 'Dominica'},
  {name: 'Grenada'},
  {name: 'Laos'},
  {name: 'St. Barth'},
  {name: 'Saint Kitts and Nevis'},
  {name: 'Greenland'},
  {name: 'Montserrat'},
  {name: 'Falkland Islands'},
  {name: 'Vatican City'},
  {name: 'Saint Pierre Miquelon'},
  {name: 'Western Sahara'},
  {name: 'MS Zaandam'},
  {name: 'Anguilla'},
  {name: 'China'},
];
